# Generated by Django 2.2.6 on 2019-10-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='current_balance',
            field=models.FloatField(max_length=4000, null=True),
        ),
    ]
