SAMPLE_DATA = [
    "Tod jenson",
    "Jan michael",
    "vincent",
    "jerrod",
    "lola",
    "arnooorrld",
    "Hiiiiiiiiiiii my name is jessica and I like sports",
    "DONT DRINK THE SALAD YOU FOOL?",
    "My name is Inigo Montoya. You killed my father. Prepare to die.",
    "I've been involved in numerous secret raids on Al-Quaeda",
    "I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed for"
    "ces. ",
    "I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands.",
    "Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States "
    "Marine Corps ",
    "As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you"
    " better prepare for the storm, maggot. ",
    "Mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again,"
    " fucker.",
    "I hate Russian dolls. They're so full of themselves.",
    "Do you remember that joke I told you about my spine",
    "I just went to an emotional wedding. Even the cake was in tiers.",
    "When's the best time to go to the dentist",
    "Today I gave my dead batteries away. They were free of charge.",
    "I went on a once-in-a-lifetime vacation. Never again.",
    "My favorite word is 'drool.' It just rolls off the tongue.",
    "I just wrote a book on reverse psychology. Do not read it.",
    "My new thesaurus is terrible. Not only that, but it's also terrible.",
    "I got fired from my job at the bank today. An old lady came in and asked me to check her balance, so I pushed her"
    " over.",
    "I wasn't going to visit my family this December, but my mom promised to make me Eggs Benedict. So I'm going home "
    "for the hollandaise.",
    "I like to spend every day as if it's my last. Staying in bed and calling for a nurse to bring me more pudding.",
    "Imagine if Americans switched from pounds to kilograms overnight. There would be mass confusion!",
    "It's inappropriate to make a 'dad joke' if you are not a dad. It's a faux pa.",
    "I have an addiction to cheddar cheese. But it's only mild.",
    "was sitting in traffic the other day.  Probably why I got run over.",
    "Sometimes I tuck my knees into my chest and lean forward. That's just how I roll.",
    "When is your door not actually a door",
    "My grandfather has the heart of a lion and a lifetime ban from the National Zoo.",
    "A communist joke isn't funny unless everyone gets it.",
    "Cosmetic surgery used to be such a taboo subject. Now you can talk about Botox and nobody raises an eyebrow.",
    "Have you heard the one about the corduroy pillow",
    "I'm thinking about removing my spine. I feel like it's only holding me back.",
    "Did you hear about the two thieves who stole a calendar",
    "I'm terrified of elevators so I'm going to start taking steps to avoid them.",
    "Have you heard of the band 923 Megabytes",
    "I used to hate facial hair but then it grew on me.",
    "I used to be addicted to the hokey pokey but then I turned myself around.",
    "I watched hockey before it was cool. They were basically swimming.",
    "There's no hole in your shoe",
    "A cowherd counted 48 cows on his property. But when he rounded them up, he had 50.",
    "When the two rabbit ears got married, it was a nice ceremony. But the reception was amazing.",
    "A chicken coup only has two doors. If it had four, it would be a chicken sedan.",
    "It's hard to teach kleptomaniacs humor. They take things so literally.",
    "Sunny-side up, scrambled, or an omelet",
    "Don't worry if you miss a gym session. Everything will work out.",
    "Ever tried to eat a clock",
    "Who can jump higher than a house",
    "Five guys walk into a bar. You think one of them would've seen it.",
    "This sweet ride has four wheels and flies. It's a garbage truck.",
    "This sentence is grammatically garbage.",
    "im cool",
    "one time I ate a shoe, date me plz",
    "Denmark is a cool place",
    "No matter how fast I run, I cannot run away from the pain...",
    "I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth",
    "Mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again,"
    " fucker.",
    "A Mississippi!",
    "Put it on my bill!",
    "Roberto!",
    "The disc-o!",
    "Wait at the buzz stop!",
    "Lemon aid!",
    "Hi Cliff!",
    "A chipmunk!",
    "Because it was soda pressing!",
    "Because people are dying to get in!",
    "Lean beef!",
    "It was about a weak back!",
    "Tooth-hurtie!",
    "A rain of terror!",
    "Because if they flew over the bay, they've bagels!",
    "Corny!",
    "Because pepper makes them sneeze!",
    "Dead ends!",
    "Because every play has a cast!",
    "Lap dogs!",
    "'Show me the honey!'",
    "Vel-crows.",
    "A steak out!",
    "It gets toad!",
    "I don't know, but its flag is a big plus!",
    "He neverlands.",
    "'Graaaaaaaains!'",
    "He needed his space.",
    "'Oh sheet!'",
    "'Cause the cow's got the udder!",
    "He felt his presents.",
    "Its butt.",
    "'Supplies!'",
    "'Robin, get in the car.'",
    "Because it's pointless!",
    "He was outstanding in his field.",
    "Bison!",
    "A blue bucket painted red.",
    "They have anty-bodies.",
    "Fssshh.",
    "To go with the traffic jam.",
    "When it's actually ajar.",
    "Grass. I lied about the wheels.",
    "A pool table.",
    "Dinner is on me!",
    "Address!",
    "Because the pee is silent.",
    "Artificial Swedener.",
    "It's making headlines.",
    "Bob.",
    "Neil.",
    "A polar bear!",
    "They each got six months.",
    "Probably not, they haven't had a gig yet.",
    "DONT DRINK THE SALAD YOU FOOL?",
    "A small medium at large.",
    "One is a crusty bus station and the other is a busty crustacean.",
    "Ten tickles.",
    "'Oops!'",
    "Then how'd you get your foot in it",
    "Because it was too tired.",
    "Because they're shellfish.",
    "'Aye, matey.'",
    "By reading a catalogue.",
    "It doesn't matter. They're all eggcellent.",
    "It's time-consuming.",
    "Pretty much anyone. (Houses can't jump.)",
    "Neither one can drive.",
    "He wanted to stake his claim.",
    "Ajar.",
    "What if Im not ready to become a sea lion?",
    "you little bitch? I'll have you know I graduated top of my class in the Navy Seals",
    "What is your favourite breakfast?",
    "Why is it important to ask good survey questions?",
    "Why do I always smell like toothpaste?",
    "Are emus offensive to anyone else? just me? ok.",
    "If you were a loser, would you tell me?",
    "What is the meaning of this!?",
    "Who let the dogs out?",
    "What do you call a hippie's wife",
    "What did the duck say when she bought a lipstick",
    "What do you call a man with a rubber toe",
    "Where did the computer go dancing",
    "What do bees do if they need a ride",
    "What do you give to a sick lemon",
    "What did the little mountain say to the bigger mountain",
    "What do you call a monkey that loves Doritos",
    "Why did the can crusher quit his job",
    "Why are there gates around cemeteries",
    "What do you call a cow with two legs",
    "What do you call a dangerous sun shower",
    "Why do seagulls fly over the sea",
    "What do you call a farm that makes bad jokes",
    "Why do fish live in salt water",
    "What streets to ghosts haunt",
    "What do you tell actors to break a leg",
    "What kind of dogs love car racing",
    "What did Winnie the Pooh say to his agent",
    "What do you call birds who stick together",
    "What do you call it when one cow spies on another",
    "What happens when a frog's car breaks down",
    "What's the best thing about Switzerland",
    "Why is Peter Pan always flying",
    "What does a zombie vegetarian eat",
    "Why didn't the astronaut come home to his wife",
    "What did the blanket say as it fell off the bed",
    "Why do cow-milking stools only have three legs",
    "How did Darth Vader know what Luke got him for Christmas",
    "What's the last thing that goes through a bug's mind when it hits a windshield",
    "What did the janitor say when he jumped out of the closet",
    "What did Batman say to Robin before they got in the car",
    "Why shouldn't you write with a broken pencil",
    "Why did the scarecrow win an award",
    "What did the buffalo say when his son left",
    "What's red and shaped like a bucket",
    "What don't ants get sick",
    "What do you call a fish with no eye",
    "Why do you smear peanut butter on the road",
    "What's green and has wheels",
    "What's green, fuzzy, and would hurt if it fell on you out of a tree",
    "What did one dish say to the other",
    "What does a house wear",
    "Why can't you hear a Pterodactyl go to the bathroom",
    "What do you call someone who immigrated to Sweden",
    "What do you call a man with no arms and no legs in a pool",
    "What do you call a man who can't stand",
    "What's the dumbest animal in the jungle",
    "What do you call a psychic little person who has escaped from prison",
    "What's the difference between a dirty bus stop and a lobster with breast implants",
    "How many tickles does it take to make an octopus laugh",
    "DONT DRINK THE SALAD YOU FOOL?",
    "What's the most terrifying word in nuclear physics",
    "Why couldn't the bicycle stand up",
    "Why don't crabs donate",
    "What did Blackbird say when he turned eighty",
    "How does your feline shop",
    "What do an apple and an orange have in common",
    "Why did the businessman invest in Smith & Wollensky",
    "What do you call a door when it's not a door",
]
