# Generated by Django 3.1.7 on 2021-03-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api2", "0003_auto_20210313_1928")]

    operations = [
        migrations.AlterField(
            model_name="transaction", name="date", field=models.DateField(db_index=True)
        )
    ]
