# Generated by Django 3.1.7 on 2021-03-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api2", "0004_auto_20210314_1810")]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="income_per_month",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="outcome_per_month",
            field=models.IntegerField(null=True),
        ),
    ]
