# Generated by Django 3.1.7 on 2021-04-05 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api2", "0006_auto_20210404_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget", name="name", field=models.CharField(max_length=20)
        ),
        migrations.AlterUniqueTogether(
            name="budget", unique_together={("name", "user")}
        ),
        migrations.AlterUniqueTogether(name="tag", unique_together={("name", "user")}),
    ]
