# Generated by Django 3.2.10 on 2022-01-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0009_auto_20220105_0529"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
