# Generated by Django 4.0.1 on 2022-03-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0014_transaction_prediction_userinfo_analyze_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="analyze_end",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="currently_calculating_predictions",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="predict_start",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="prediction_state_hash",
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="analyze_start",
            field=models.DateField(
                help_text="Date to start analyzing transaction behaviour from",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="predict_end",
            field=models.DateField(
                help_text="Date to stop predicting transactions for", null=True
            ),
        ),
    ]
