# Generated by Django 4.0.1 on 2022-07-03 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0015_remove_userinfo_analyze_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="common_budget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api2.budget",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="common_transaction_amount",
            field=models.IntegerField(null=True),
        ),
    ]
