# Generated by Django 4.0.1 on 2022-09-08 14:42

from django.db import migrations, models
import django.db.models.deletion

from api2.custom_migrations.budget_tree.EnsureRootBudget import EnsureRootBudget


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0017_budget_parent"),
    ]

    operations = [
        EnsureRootBudget.get_operation()
    ]
