# Generated by Django 4.0.1 on 2022-09-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0019_remove_initial_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='initial_balance',
        ),
    ]
