# Generated by Django 4.0.1 on 2022-09-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0022_set_monthly_allocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='percentage',
        ),
    ]
