# Generated by Django 4.0.1 on 2022-09-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0023_remove_budget_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="is_node",
            field=models.BooleanField(default=False),
        ),
    ]
