# Generated by Django 4.0.1 on 2022-09-12 16:43

from django.db import migrations, models
import django.utils.timezone

from api2.custom_migrations.budget_tree.SetupCreatedAndModifiedTime import SetupCreatedAndModifiedTime


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0024_budget_is_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        SetupCreatedAndModifiedTime.get_operation()
    ]
