# Generated by Django 4.0.1 on 2022-10-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0025_transaction_created_transaction_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='darkMode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='theme',
            field=models.CharField(default='CLASSIC', max_length=20),
        ),
    ]
