#!/bin/bash

source venv/bin/activate

./scripts/local_db.sh
./scripts/migrate.sh
./scripts/load_budgets.sh

python3 manage.py createsuperuser --username dev --email ''
python3 manage.py generate_transactions 10 10 --save
