#!/usr/bin/env python
import os
import sys

code_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(code_dir)

os.environ.setdefault('DJANGO_SETTINGS_MODULE', "budget.settings")

import django
django.setup()


from api2.models import *

import code
code.interact(local=globals())

